version: '3.8'

services:
  mongo:
    image: mongo:latest
    hostname: evraz-mongodb
    container_name: evraz-mongodb
    restart: unless-stopped
    env_file: ".env"
    ports:
      - "${MONGO_PORT:-27017}:${MONGO_PORT:-27017}"
    volumes:
      - ./data:/data/db
    networks:
      - mutagen-evraz-backend

networks:
  mutagen-backend:
    external: true
    name: mutagen-evraz-backend